# Generated by Django 3.1.5 on 2021-02-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='detail',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
