# Generated by Django 3.1.5 on 2021-03-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obito', '0002_image_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=10)),
                ('video', models.FileField(upload_to='video/%y')),
                ('thumb', models.FileField(upload_to='thumb/%y')),
            ],
        ),
    ]
